### ISSUE TITLE
Error handling best practices!

### ISSUE THREAD

**Issue by KGmajor** [pakawaka1/YearOneMovieList#42]
https://github.com/pakawaka1/YearOneMovieList/blob/1aecec390af60ea9391a878a238e2ef193131427/controllers/movies.js#L28

Try -> Catch is by default synchronous. Since you're calling this async function from the route, you may need to add some extra handling there. Check out this article. http://expressjs.com/en/guide/error-handling.html

**Comment by pakawaka1** [comment]
Still need to redirect route back to base URL in no movie found.

**Comment by pakawaka1** [comment]
If movie is not found, status code is issued, then route redirect back to the landing page.
